### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by baopham**
For people who copy and paste examples.

### CODE REVIEW

**Comment by huytd** [comment]
🤔 in this case I think we better change the code to handle `'` character instead of forcing user put a `\'` themself

**Comment by baopham** [comment]
hmmm yeah, that's a good idea.

**Comment by baopham** [comment]
Not sure if it's possible since that is done at the terminal level - putting a single quote `'` triggers the multi line mode. Unless we allow users to use double quotes to wrap their query?

**Comment by huytd** [comment]
Ah I see... Didn't notice that, my bad.

Going against the terminal would be hard, adding double quotes is not a good solution as well (I bet you don't want to use double quote to search if you're the user).

Let's just merge this PR and we will find another solution for this later.

Thank you so much 👍

**Pull request merged**
