### PR TITLE
Update tag regex to consider for additional attributes

### PR DESCRIPTION
**Pull request by baopham**
Some answers would get: `<pre class="lang-js prettyprint-override">`

### CODE REVIEW

**Comment by baopham** [comment]
We probably have to do the same for other tags, what do you think?

**Comment by huytd** [comment]
Nice one! Thanks for catching that! Yeah I think we should do the same with other tags, could you update a new commit to this PR for that please?

**Comment by baopham** [comment]
Yep, will do.

**Comment by baopham** [comment]
@huytd Let me know if you have any concern about the change.

**Comment by huytd** [comment]
It's ok for me 👍

**Pull request merged**
